services:
  - type: web
    name: cloudripper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "app:create_app()" --config gunicorn.conf.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SOUNDCLOUD_CLIENT_ID
        sync: false # This will be set manually in Render's dashboard
      - key: SECRET_KEY
        generateValue: true # This will auto-generate a secure key
      - key: DATABASE_URL
        sync: false # This will be set manually in Render's dashboard
